### ISSUE TITLE
Addon does not start after Update

### ISSUE THREAD

**Issue by pLeXwithFleX** [elbowz/partymode-autostart-xbmc-service#6]
Im using Libreelec 8.0.2 (Kodi 17.3) and my Kodi updated the partymode addon today. After a reboot, the addon is not working anymore. Partymode Update is installed 0.9.0b and on any reboot i can find the following error in the kodi.log file:

22:18:42.073 T:139758302918400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.partymode.autostart/PartymodeAutostart.py", line 193, in <module>
                                                Main()
                                              File "/storage/.kodi/addons/service.partymode.autostart/PartymodeAutostart.py", line 33, in __init__
                                                self.serviceMonitor = serviceMonitor(self._getSettings(), self._onScreensaverAction)
                                              File "/storage/.kodi/addons/service.partymode.autostart/PartymodeAutostart.py", line 60, in _getSettings
                                                self.playbackRandom                             = int(__addon__.getSetting('playback-random'))
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--

**Comment by admirableadmin** [comment]
Same here on OpenELEC 7.0.1 (Kodi 16.1) after updating partymode 0.8.8b to 0.9.0b.
For a workaround in partymode autostart it helps to reset the settings with the standard button and reconfigure them.

**Comment by elbowz** [comment]
I'm really sorry...I have accepted a new pull request without test it (no free time).

@andpei thanks for your fix..I'll merge it soon

**Comment by eslindsey** [comment]
Sorry for the oversight of not providing default values for these new settings. I am not certain why this issue would not present during development--without the default values, I should have run across this problem myself as soon as I introduced the new settings, but I did not.
