### ISSUE TITLE
Kodi Leia V18.9 CEC Adapter conflict

### ISSUE THREAD

**Issue by EnsoftCo** [elbowz/partymode-autostart-xbmc-service#8]
Hi,

I had a conflict with the partymode-autostart and the CEC adapter.

When both were enabled Kodi would get stuck on start screen with CEC adapter message displayed.
There was no way of getting out of it, rebooting didn't help either.

Eventually I connect to my Pi with FileZilla (SFTP), found the settings file and set the partymode to "false".
After that I rebooted the Pi and it worked again.

I have now disabled the CEC adapter in the Settings-System-Input-Peripherals menu because I don't need it anyway and it fixed my problem.

I'm running a Pi 3B+ with USB audio stick an a Medion desktop monitor connect through HDMI.

I have no idea how to fix this but just thought I'd share my issue in case anybody else has the same problem.

**Comment by elbowz** [comment]
The addon is discontinued...ie. I don't use it anymore, sorry.

PR and fork are welcome

**Comment by elbowz** [comment]
I have spent some times to this old project, but I can't reproduce your issue without the "CEC adapter".

If you are still interested, try to install this version manually:
[party-mode-autostart-no-startup-dlg.zip](https://github.com/elbowz/partymode-autostart-xbmc-service/files/5649151/party-mode-autostart-no-startup-dlg.zip)

it's only a gamble
