### ISSUE TITLE
partymode freezes kodi when used

### ISSUE THREAD

**Issue by janneman001** [elbowz/partymode-autostart-xbmc-service#9]
Kodi 18.7 freezes kodi after countdown when it starts the playlist or music mix

**Comment by elbowz** [comment]
The addon is discontinued...ie. I don't use it anymore, sorry.

PR and fork are welcome

**Comment by elbowz** [comment]
I have checked out the add-on on Kodi 18.9 (Linux) all seems works like expected.
Try to update Kodi to latest version
